### ISSUE TITLE
Possible GFX corruption

### ISSUE THREAD

**Issue by ReadyPlayer29** [Kitrinx/Atari7800_MiSTer#5]
Cant verify this on real hardware but the PAL Version of Kung Fu Master appears to have corrupted gfx on titlescreen.  The text, its easy to spot.

Have tried it on PAL and AUTO settings and it does it on both.

The NTSC version screen appears fine.

**Comment by Kitrinx** [comment]
I'll have to find someone with a PAL console and dragonfly cart to confirm that one.

**Comment by Kitrinx** [comment]
I can't find anyone with a PAL 7800, but I believe this video is PAL on a 7800:
https://www.youtube.com/watch?app=desktop&v=dwLwD7vGVI8

If you look closely you can see that it also has the corruption:
![image](https://user-images.githubusercontent.com/15653832/115481793-38b5b980-a202-11eb-9ca7-be45ae84ffb1.png)

In addition all the emulators I have tried also have the same pattern.

![image](https://user-images.githubusercontent.com/15653832/115481861-4ff4a700-a202-11eb-87cc-bc48fc6468d8.png)

compare to the core:
![PIC-2021_04_20_19_25_22](https://user-images.githubusercontent.com/15653832/115481894-5c78ff80-a202-11eb-9259-13b7b71127cd.png)

I don't think it's likely that this is a bug, but rather just an artifact from a sloppy PAL port in the original game.
